/* Public portfolio copy derived from Hugo's supplied resume. Keep facts here. */
'use strict';
window.HugoLocale = (() => {
  const KEY='hugo-os.language.v1';
  const allowed=['zh-TW','en'];
  const query=new URLSearchParams(location.search).get('lang');
  let saved='';try{saved=localStorage.getItem(KEY)||'';}catch{}
  let language=allowed.includes(query)?query:allowed.includes(saved)?saved:(navigator.language||'').toLowerCase().startsWith('zh')?'zh-TW':'en';
  function set(next,{updateURL=true}={}){
    language=allowed.includes(next)?next:'en';
    document.documentElement.lang=language;
    try{localStorage.setItem(KEY,language);}catch{}
    if(updateURL){const url=new URL(location.href);url.searchParams.set('lang',language);history.replaceState(null,'',url.pathname+url.search+url.hash);}
    window.dispatchEvent(new CustomEvent('hugo:language',{detail:{language}}));
  }
  document.documentElement.lang=language;
  return {get language(){return language;},set};
})();

window.HUGO_CONTENT = {
  'zh-TW': {
    seo:{title:'HUGO OS — 蕭宏輝的工程履歷',description:'蕭宏輝（Hugo）— 後端工程師與工程管理者。10+ 年軟體開發、8+ 年 Golang、5+ 年團隊管理經驗。'},
    ui:{
      apps:{welcome:'履歷總覽',about:'關於 Hugo',experience:'工作經歷',projects:'專案案例',terminal:'終端機',skills:'專業技能',resume:'履歷 PDF',contact:'聯絡方式',browser:'瀏覽器',files:'檔案',settings:'設定'},
      visitor:'訪客',desktop:'桌面',applications:'應用程式',workspace:'Hugo 的工作空間',shutdown:'關機',apps:'應用程式',startHere:'從這裡開始',caseStudies:'專案案例',shortcuts:'桌面捷徑',allApps:'所有應用程式',taskbar:'工作列',showDesktop:'顯示桌面',settings:'開啟設定',switchLanguage:'Switch to English',skip:'略過開場',scroll:'捲動探索',caption:'後端工程\n以及打造系統的人',signature:'個人工程工作空間'
    },
    metrics:[['10+','年','軟體開發經驗'],['8+','年','Golang 經驗'],['5+','年','工程團隊管理']],
    welcome:{eyebrow:'履歷總覽 · 後端工程 / 工程管理',headline:'打造可靠的後端系統，<span>也帶領團隊穩定交付。</span>',summary:'我是蕭宏輝（Hugo），一位從遊戲與即時系統走向 Golang 後端與工程管理的工程師。我的經驗涵蓋微服務、資料庫、訊息佇列、Kubernetes、正式環境維運，以及跨團隊技術規劃。',primary:'查看代表案例',secondary:'快速閱讀履歷',footer:'核心領域：Golang · MySQL · Redis · RabbitMQ · Kubernetes · GCP',about:'了解我的工作方式',sectionSummary:'專業摘要',sectionCareer:'職涯摘要',sectionProjects:'代表專案',sectionSkills:'核心能力',sectionCredentials:'學歷與肯定',allExperience:'完整工作經歷',allProjects:'查看所有案例',contactLabel:'聯絡我'},
    about:{kicker:'01 / 程式背後的工程師',title:'可靠的系統，來自清楚的判斷與協作。',intro:'我從即時遊戲、通訊服務一路走到 Golang 微服務與工程管理，喜歡把複雜問題拆成可以理解、驗證與維運的系統。',engineeringTitle:'讓複雜度可以被管理',engineering:'我關注服務邊界、資料正確性、併發、效能與故障恢復。先釐清失敗模式，再用指標與實際流量驗證設計。',leadershipTitle:'讓團隊能持續做出好決定',leadership:'我的工作包含需求確認、技術規劃、Code Review、跨單位上線協作、線上問題排查、招募面試與內部教學。',journey:'查看完整職涯'},
    experience:{kicker:'02 / 工作經歷',title:'從產品開發到工程管理。',intro:'10+ 年橫跨遊戲、即時通訊、後端平台與工程團隊管理的實務經驗。',note:'以下內容整理自目前履歷；公司機密與未提供的內部數據維持匿名，不額外推測。',years:{
      '2015':{role:'軟體工程師',company:'嘉碼科技 · 2015.12–2016.05',bullets:['維護與擴充 Dealer、Pit、Vault、Cashier 等賭場管理 Client／Server 系統。','使用 JavaFX、Node.js、MSSQL 與 ActiveMQ 建立即時營運功能。']},
      '2016':{role:'遊戲工程師',company:'玹漢數位科技 · 2016.07–2017.05',bullets:['以 Unity、Node.js、Socket.IO 與 MongoDB 開發即時對戰手機遊戲。','負責 Client 幀同步物理、REST API 串接、配對房間與即時戰鬥指令同步。']},
      '2017':{role:'研發工程師',company:'睿莊科技 · 2017.06–2019.04',bullets:['從 Cocos2d-js 遊戲 Client 延伸到 Golang 通訊服務、Kubernetes 部署與遊戲管理後台。','獨立開發 Node.js 壓力測試工具，驗證單台伺服器可支援 30,000 人同時上線。']},
      '2019':{role:'總工程師 → 副處長',company:'公司名稱保密 · 2019.05–2026.09',bullets:['帶領團隊規劃會員推廣與活動系統的微服務架構、需求確認、上線協作與線上維運。','系統服務量達 QPS 2,000–5,000；Latency P50 35ms、P90 85ms、P99 390ms。','擔任後端招募面試官與公司內部後端講師。']}
    },verified:'履歷已提供的公司、期間與成果'},
    projects:{
      kicker:'03 / 代表專案',all:'所有案例',backend:'工程專案',portfolio:'個人作品',name:'名稱',type:'類型',items:'個案例',open:'開啟案例',back:'返回所有案例',implemented:'已實作作品',real:'正式環境專案',side:'SIDE PROJECT',labels:['問題','規模與架構','我的職責','關鍵挑戰','做法','成果'],
      entries:[
        {title:'會員推廣平台',short:'會員推廣平台',kind:'real',stack:['Golang','MySQL','MongoDB','Redis','RabbitMQ','GCP','Kubernetes'],problem:'需要支援遊戲產品的會員推廣機制，同時處理高流量、跨服務資料與持續變動的活動需求。',architecture:'以 Golang 微服務拆分領域能力，MySQL／MongoDB 保存不同型態資料，Redis 支援高頻存取，RabbitMQ 處理非同步工作，部署於 GCP Kubernetes。',role:'帶領團隊進行需求確認、內部微服務架構規劃、跨單位上線架構對接、線上維運與資料排查，並參與後端招募。',challenges:'在產品快速迭代下維持服務邊界、資料一致性與可觀測性，同時確保跨單位上線資訊一致。',solution:'以明確的服務責任、訊息佇列與快取策略承接流量，並把需求確認、部署規劃與正式環境排查納入同一套交付流程。',result:'服務量達 QPS 2,000–5,000；Latency P50 35ms、P90 85ms、P99 390ms，並支援提升玩家押碼量與留存相關的產品目標。'},
        {title:'活動平台',short:'活動平台',kind:'real',stack:['Golang','MySQL','MongoDB','RabbitMQ','GCP','Kubernetes'],problem:'多種遊戲活動需要可重複使用的後端能力，避免每個活動各自實作而增加維護成本。',architecture:'以 Golang 建立活動領域服務，透過 MySQL／MongoDB 保存活動與進度資料，RabbitMQ 承接非同步處理，部署於 GCP Kubernetes。',role:'帶領團隊確認押碼王、龍虎榜等需求，規劃活動架構，並與其他單位討論上線與串接方式。',challenges:'活動規則差異大、時程集中，且需要和既有遊戲及會員資料正確整合。',solution:'抽離共通活動流程與可配置規則，將高變動產品邏輯和核心資料責任分開。',result:'建立可持續擴充的活動系統基礎，支援多種活動需求；更精確的成效數字待後續補充。'},
        {title:'即時視訊遊戲整合',short:'即時視訊遊戲',kind:'real',stack:['Golang','MariaDB','MongoDB','Redis','WebSocket'],problem:'自製視訊遊戲同時需要內部局單管理、低延遲牌訊傳輸，以及多家外部視訊來源整合。',architecture:'Golang 微服務負責遊戲與局單資料，MariaDB／MongoDB 保存狀態，Redis 支援即時資料，WebSocket 對外推送牌訊。',role:'規劃內部微服務架構、負責局單資訊管理、提供 WebSocket 牌訊並整合多家視訊來源。',challenges:'不同來源的事件格式、連線狀態與到達順序不一致，需要統一成穩定的內部模型。',solution:'建立清楚的整合邊界與正規化流程，讓外部來源差異不直接滲透到核心服務。',result:'完成自製視訊遊戲與多家牌訊整合；吞吐與可用性數據待後續補充。'},
        {title:'遊戲連線壓力測試工具',short:'30K 連線壓測',kind:'real',stack:['Node.js','WebSocket'],problem:'遊戲上線前需要知道單台伺服器可以承受多少同時在線玩家，但原有 Client 不適合大量自動化測試。',architecture:'將 Client 連線與進房流程改寫成 Node.js 測試程式，自動建立大量 WebSocket 連線並模擬玩家進入遊戲。',role:'獨立設計與開發測試工具，運用既有 Client 底層連線經驗重建多人同時上線流程。',challenges:'需要在不啟動完整圖形 Client 的情況下，正確重現協議、連線生命週期與遊戲流程。',solution:'抽離必要的通訊流程，以輕量 Node.js worker 建立可控制的併發連線與遊戲操作。',result:'實測單台伺服器可支援 30,000 人同時上線。'},
        {title:'拍賣訂標系統',short:'拍賣訂標系統',kind:'side',stack:['Golang','Next.js','MySQL','MongoDB','Docker Compose','Consul'],problem:'拍賣商品的價格、競標網站與財務資訊分散，需要集中管理並持續監測價格。',architecture:'以 Golang 建立後端服務、Next.js 建立操作介面，MySQL／MongoDB 保存交易與商品資料，並以 Docker Compose、Consul 管理服務。',role:'涵蓋自製訂標集群、競標網站價格監測、動態競標出價、物品管理、財務系統與用戶收支系統。',challenges:'需同步處理多來源價格變化、動態出價與使用者收支紀錄。',solution:'將價格收集、監控、出價與財務能力拆成明確模組，集中保存商品和交易狀態。',result:'Side Project 持續開發期間為 2023.12–2026.03；量化成果待後續補充。'},
        {title:'HUGO OS 個人工程工作空間',short:'HUGO OS',kind:'portfolio',stack:['JavaScript','HTML','CSS','Three.js'],problem:'傳統履歷不容易同時呈現工程經歷、系統設計思路與個人風格。',architecture:'以靜態 HTML、原生 JavaScript 視窗系統與延遲載入的 Three.js 開場組成，所有核心素材皆可本地執行。',role:'作品概念、資訊架構、互動設計與前端實作。',challenges:'在保留 3D 敘事與桌面互動的同時，仍需支援鍵盤、行動裝置、低效能設備與離線開啟。',solution:'將履歷內容拆成獨立 App，3D 場景只服務開場並在進入桌面後釋放，同時提供 reduced-motion 與輕量 fallback。',result:'完成可直接開啟的互動式作品集、終端機導覽、專案案例瀏覽與 GitHub Pages 部署流程。'}
      ]
    },
    skills:{kicker:'06 / 專業技能',title:'工具跟著問題走。',intro:'不使用任意熟練度分數；以下是履歷中實際使用過的技術與工作領域。',groups:[
      ['後端',['Golang','Python','Node.js','PHP','REST','WebSocket'],'後端服務、API 與即時連線開發。'],
      ['資料與訊息',['MySQL','MariaDB','MongoDB','Redis','RabbitMQ','ActiveMQ'],'資料建模、快取、交易與非同步處理。'],
      ['基礎設施',['Linux','Docker','Kubernetes','GCP','Consul','Jenkins'],'部署、服務發現、CI/CD 與正式環境維運。'],
      ['可觀測性',['Kibana','Elasticsearch'],'線上查詢、異常排查與恢復。'],
      ['產品開發',['Unity','Cocos2d-js','Next.js','JavaScript'],'從遊戲 Client 到個人工具與互動網站。'],
      ['工程管理',['Team Leadership','Technical Planning','Hiring','Code Review','Cross-team Delivery'],'需求確認、架構規劃、招募、教學與跨單位交付。']
    ]},
    resume:{kicker:'07 / 履歷 PDF',title:'快速閱讀版本。',intro:'先以現有 PDF 作為完整資料來源；網站內提供較適合快速掃讀的摘要。',download:'下載目前履歷 PDF',preview:'另開 PDF 預覽',draft:'公開履歷摘要',role:'後端工程師 / 工程管理者',profileTitle:'個人摘要',profile:'10+ 年軟體開發經驗，從遊戲與即時通訊系統走向 Golang 微服務與工程管理，負責架構規劃、正式環境維運、跨團隊上線與人才招募。',metrics:'10+ 年軟體開發\n8+ 年 Golang\n5+ 年工程團隊管理',technologyTitle:'核心技術',technology:'Golang · MySQL · MongoDB · Redis · RabbitMQ · Docker · Kubernetes · GCP · WebSocket',leadershipTitle:'工程與領導',leadership:'System Design · Performance · Production Operations · Team Leadership · Technical Planning · Hiring · Internal Training',experienceTitle:'代表經歷',experience:'總工程師升任副處長；帶領會員推廣與活動平台開發；高流量服務達 QPS 2,000–5,000；獨立壓測驗證單台 30,000 人同時上線。',note:'此版本只使用目前履歷中已提供的內容；後續可再補上團隊規模、可公開成果與職涯目標。'},
    contact:{kicker:'08 / 聯絡方式',title:'一起把複雜問題變得清楚。',intro:'歡迎針對後端工程、Golang、系統設計與工程管理職務聯絡。',missing:'尚未提供公開連結',note:'Email 來自你提供的履歷；GitHub 與 LinkedIn 尚待補充。'},
    education:{award:'全國技藝競賽 程式設計組第三名',university:'國立雲林科技大學 資訊管理系',training:'公司內部後端講師'}
  },
  en: {
    seo:{title:"HUGO OS — Hugo's engineering profile",description:'Hugo (蕭宏輝) — Backend Engineer and Engineering Manager with 10+ years in software, 8+ years in Golang, and 5+ years leading engineering teams.'},
    ui:{
      apps:{welcome:'Profile Overview',about:'About Hugo',experience:'Experience',projects:'Case Studies',terminal:'Terminal',skills:'Skills',resume:'Resume PDF',contact:'Contact',browser:'Browser',files:'Files',settings:'Settings'},
      visitor:'Visitor',desktop:'Desktop',applications:'Applications',workspace:"Hugo's workspace",shutdown:'Shut down',apps:'Apps',startHere:'Start here',caseStudies:'Case studies',shortcuts:'Desktop shortcuts',allApps:'All applications',taskbar:'Taskbar',showDesktop:'Show desktop',settings:'Open settings',switchLanguage:'切換至中文',skip:'Skip intro',scroll:'Scroll to explore',caption:'BACKEND ENGINEERING\nAND THE PEOPLE BEHIND IT',signature:'PERSONAL ENGINEERING WORKSPACE'
    },
    metrics:[['10+','YEARS','Software engineering'],['8+','YEARS','Building with Golang'],['5+','YEARS','Engineering leadership']],
    welcome:{eyebrow:'PROFILE OVERVIEW · BACKEND / LEADERSHIP',headline:'Reliable backend systems.<br><span>Engineering teams built to deliver.</span>',summary:'I’m Hugo (蕭宏輝), an engineer whose path spans real-time games, Golang backend systems, and engineering management. My experience covers microservices, databases, messaging, Kubernetes, production operations, and cross-team technical planning.',primary:'Explore case studies',secondary:'View résumé',footer:'Core: Golang · MySQL · Redis · RabbitMQ · Kubernetes · GCP',about:'How I work',sectionSummary:'Professional summary',sectionCareer:'Career snapshot',sectionProjects:'Selected work',sectionSkills:'Core capabilities',sectionCredentials:'Education & recognition',allExperience:'Full experience',allProjects:'View all case studies',contactLabel:'Contact'},
    about:{kicker:'01 / THE ENGINEER BEHIND THE SYSTEM',title:'Reliable systems start with clear decisions and strong collaboration.',intro:'My career has moved from real-time games and communication services to Golang microservices and engineering management. I enjoy turning complex problems into systems that teams can understand, validate, and operate.',engineeringTitle:'Make complexity manageable',engineering:'I focus on service boundaries, data correctness, concurrency, performance, and recovery. I start with failure modes, then validate the design with metrics and real traffic.',leadershipTitle:'Help teams make good decisions consistently',leadership:'My scope includes requirements, technical planning, code review, cross-team launches, production troubleshooting, hiring, and internal backend training.',journey:'Explore the full journey'},
    experience:{kicker:'02 / EXPERIENCE',title:'From product engineering to engineering leadership.',intro:'10+ years across games, real-time communication, backend platforms, and engineering team leadership.',note:'Based on the supplied résumé. Confidential company information and unavailable internal metrics remain undisclosed.',years:{
      '2015':{role:'Software Engineer',company:'嘉碼科技 · Dec 2015–May 2016',bullets:['Maintained and expanded client/server systems for dealer, pit, vault, and cashier operations.','Built real-time operational features with JavaFX, Node.js, MSSQL, and ActiveMQ.']},
      '2016':{role:'Game Engineer',company:'玹漢數位科技 · Jul 2016–May 2017',bullets:['Developed a real-time mobile strategy game with Unity, Node.js, Socket.IO, and MongoDB.','Owned client frame-sync physics, REST integrations, room matching, and real-time battle command synchronization.']},
      '2017':{role:'R&D Engineer',company:'睿莊科技 · Jun 2017–Apr 2019',bullets:['Expanded from Cocos2d-js game clients into Golang communication services, Kubernetes delivery, and game operations tooling.','Independently built a Node.js load-test tool that validated 30,000 concurrent users on a single server.']},
      '2019':{role:'Chief Engineer → Deputy Department Head',company:'Confidential company · May 2019–Sep 2026',bullets:['Led requirements, microservice architecture, cross-team launch planning, production operations, and data investigation for referral and campaign platforms.','Operated at 2,000–5,000 QPS with latency of P50 35 ms, P90 85 ms, and P99 390 ms.','Served as a backend interviewer and internal backend instructor.']}
    },verified:'Roles, dates, and outcomes supplied in the résumé'},
    projects:{
      kicker:'03 / SELECTED WORK',all:'All case studies',backend:'Engineering work',portfolio:'Portfolio',name:'Name',type:'Type',items:'case studies',open:'Open case study',back:'All case studies',implemented:'IMPLEMENTED PORTFOLIO',real:'PRODUCTION PROJECT',side:'SIDE PROJECT',labels:['Problem','Scale & architecture','My role','Key challenges','Approach','Outcome'],
      entries:[
        {title:'Member referral platform',short:'Referral platform',kind:'real',stack:['Golang','MySQL','MongoDB','Redis','RabbitMQ','GCP','Kubernetes'],problem:'The product needed a scalable member referral system that could handle high traffic, cross-service data, and frequently changing campaign requirements.',architecture:'Golang microservices separated domain responsibilities. MySQL and MongoDB stored different data models, Redis served high-frequency access, RabbitMQ handled asynchronous work, and workloads ran on GCP Kubernetes.',role:'Led requirements, internal microservice architecture, cross-team launch integration, production operations, data investigation, and backend hiring.',challenges:'Maintaining clear service ownership, data consistency, and observability while product requirements evolved quickly across teams.',solution:'Combined explicit service responsibilities with messaging and caching strategies, and treated requirements, deployment planning, and production troubleshooting as one delivery loop.',result:'Handled 2,000–5,000 QPS with latency of P50 35 ms, P90 85 ms, and P99 390 ms, supporting product initiatives tied to player engagement and retention.'},
        {title:'Campaign platform',short:'Campaign platform',kind:'real',stack:['Golang','MySQL','MongoDB','RabbitMQ','GCP','Kubernetes'],problem:'Multiple game campaigns needed reusable backend capabilities instead of separate one-off implementations that would increase maintenance cost.',architecture:'Golang services owned campaign logic, MySQL and MongoDB stored definitions and progress, RabbitMQ handled asynchronous work, and services ran on GCP Kubernetes.',role:'Led requirement clarification for ranking and engagement campaigns, planned the architecture, and coordinated launch and integration with other teams.',challenges:'Campaign rules varied significantly, timelines overlapped, and each campaign had to integrate correctly with existing game and member data.',solution:'Separated common campaign workflows and configurable rules from high-change product logic and core data ownership.',result:'Established a reusable foundation for multiple campaign formats. More detailed outcome metrics can be added when available for public use.'},
        {title:'Real-time video game integration',short:'Real-time video platform',kind:'real',stack:['Golang','MariaDB','MongoDB','Redis','WebSocket'],problem:'A first-party live game needed internal round management, low-latency event delivery, and integration with multiple external video feeds.',architecture:'Golang microservices owned game and round data, MariaDB and MongoDB stored state, Redis supported real-time access, and WebSocket delivered events to clients.',role:'Planned the internal microservice architecture, managed round data, provided external WebSocket events, and integrated multiple video sources.',challenges:'Each source had different event formats, connection behavior, and ordering guarantees, requiring a stable internal representation.',solution:'Created explicit integration boundaries and normalization flows so external variation did not leak into core services.',result:'Delivered the first-party live game and multi-provider event integration. Throughput and availability metrics can be added later.'},
        {title:'Game connection load-test tool',short:'30K connection test',kind:'real',stack:['Node.js','WebSocket'],problem:'Before launch, the team needed evidence of how many concurrent players one server could support, but the full graphical client was unsuitable for automated scale testing.',architecture:'Reimplemented the client connection and room-entry flow as a Node.js test tool that opened large numbers of WebSocket sessions and simulated users entering games.',role:'Independently designed and built the tool, applying prior client networking knowledge to reproduce the multiplayer connection flow.',challenges:'The test had to reproduce protocol details, connection lifecycles, and game actions without launching complete graphical clients.',solution:'Extracted the required communication flow into lightweight Node.js workers with controlled concurrent connections and actions.',result:'Validated 30,000 concurrent users on a single server.'},
        {title:'Auction bidding system',short:'Auction bidding system',kind:'side',stack:['Golang','Next.js','MySQL','MongoDB','Docker Compose','Consul'],problem:'Auction pricing, bidding websites, and financial records were fragmented and needed centralized management with continuous price monitoring.',architecture:'Golang services powered the backend, Next.js provided the interface, MySQL and MongoDB stored transaction and product data, and Docker Compose with Consul managed the services.',role:'Covered a custom bidding cluster, auction-site price monitoring, dynamic bidding, item management, finance, and user income and expense tracking.',challenges:'The system needed to coordinate changing prices from multiple sources, dynamic bids, and user financial records.',solution:'Separated price collection, monitoring, bidding, and finance into explicit modules with centralized product and transaction state.',result:'Developed as a side project from Dec 2023 to Mar 2026. Quantified outcomes can be added later.'},
        {title:'HUGO OS personal engineering workspace',short:'HUGO OS',kind:'portfolio',stack:['JavaScript','HTML','CSS','Three.js'],problem:'A traditional résumé makes it difficult to present engineering experience, systems thinking, and personal character in one place.',architecture:'A static HTML desktop, native JavaScript application windows, and a lazily loaded Three.js opening. Core assets ship locally.',role:'Portfolio concept, information architecture, interaction design, and frontend implementation.',challenges:'Preserving the cinematic desktop experience while supporting keyboard navigation, mobile devices, lower-end hardware, and direct offline opening.',solution:'Separated résumé content into apps, limited the 3D scene to the opening, released GPU resources after entry, and provided reduced-motion and lightweight fallbacks.',result:'Delivered a directly openable interactive portfolio with terminal navigation, case-study browsing, and GitHub Pages deployment.'}
      ]
    },
    skills:{kicker:'06 / SKILLS',title:'The tools follow the problem.',intro:'No arbitrary proficiency scores - only technologies and responsibilities used in real work.',groups:[
      ['BACKEND',['Golang','Python','Node.js','PHP','REST','WebSocket'],'Backend services, APIs, and real-time connections.'],
      ['DATA & MESSAGING',['MySQL','MariaDB','MongoDB','Redis','RabbitMQ','ActiveMQ'],'Data modeling, caching, transactions, and asynchronous processing.'],
      ['INFRASTRUCTURE',['Linux','Docker','Kubernetes','GCP','Consul','Jenkins'],'Delivery, service discovery, CI/CD, and production operations.'],
      ['OBSERVABILITY',['Kibana','Elasticsearch'],'Production investigation, diagnosis, and recovery.'],
      ['PRODUCT ENGINEERING',['Unity','Cocos2d-js','Next.js','JavaScript'],'From game clients to personal tools and interactive web experiences.'],
      ['ENGINEERING LEADERSHIP',['Team Leadership','Technical Planning','Hiring','Code Review','Cross-team Delivery'],'Requirements, architecture, hiring, teaching, and cross-team execution.']
    ]},
    resume:{kicker:'07 / RESUME PDF',title:'The quick-reading version.',intro:'The supplied PDF remains the complete source; this app presents a scan-friendly summary for the web.',download:'Download current résumé',preview:'Open PDF preview',draft:'PUBLIC PROFILE SUMMARY',role:'Backend Engineer / Engineering Manager',profileTitle:'PROFILE',profile:'10+ years in software engineering, progressing from games and real-time communications to Golang microservices and engineering management across architecture, production operations, cross-team launches, and hiring.',metrics:'10+ years in software development\n8+ years with Golang\n5+ years in engineering leadership',technologyTitle:'CORE TECHNOLOGIES',technology:'Golang · MySQL · MongoDB · Redis · RabbitMQ · Docker · Kubernetes · GCP · WebSocket',leadershipTitle:'ENGINEERING & LEADERSHIP',leadership:'System Design · Performance · Production Operations · Team Leadership · Technical Planning · Hiring · Internal Training',experienceTitle:'SELECTED EXPERIENCE',experience:'Promoted from Chief Engineer to Deputy Department Head; led referral and campaign platforms; operated services at 2,000–5,000 QPS; independently validated 30,000 concurrent users on one server.',note:'This version uses only details supplied in the current résumé. Team size, additional public outcomes, and future role goals can be added later.'},
    contact:{kicker:'08 / CONTACT',title:'Let’s make complex systems easier to understand and operate.',intro:'Open to conversations about backend engineering, Golang, systems design, and engineering leadership roles.',missing:'Public link not provided yet',note:'The email address comes from the supplied résumé. GitHub and LinkedIn can be added later.'},
    education:{award:'3rd place, National Vocational High School Skills Competition - Programming',university:'Information Management, National Yunlin University of Science and Technology',training:'Internal backend instructor'}
  }
};
